### ISSUE TITLE
MessagePack::MalformedFormatError is caused from data source by fluentd v0.14

### ISSUE THREAD

**Issue by cubicdaiya** [norikra/fluent-plugin-norikra#15]
If a data source comes from fluentd v0.14, fluent-plugin-norikra outputs errors like below when it inputs data source to Norikra. (FYI. The version fluentd equipped fluent-plugin-norikra is v0.12)

```
2017-03-07 09:00:00 +0000 [error]: forward error error=#<MessagePack::MalformedFormatError: invalid byte> error_class=MessagePack::MalformedFormatError
  2017-03-07 09:00:00 +0000 [error]: suppressed same stacktrace
2017-03-07 09:00:00 +0000 [warn]: emit transaction failed: error_class=MessagePack::MalformedFormatError error="invalid byte" tag="some_log"
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/event.rb:149:in `feed_each'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/event.rb:149:in `each'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-norikra-0.4.2/lib/fluent/plugin/norikra/output.rb:160:in `format_stream'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/output.rb:269:in `emit'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/event_router.rb:90:in `emit_stream'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_forward.rb:165:in `on_message'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_forward.rb:301:in `call'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_forward.rb:301:in `block in on_read_msgpack'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_forward.rb:300:in `feed_each'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_forward.rb:300:in `on_read_msgpack'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.5/lib/cool.io/io.rb:123:in `on_readable'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.5/lib/cool.io/io.rb:186:in `on_readable'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run_once'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run'
  2017-03-07 09:00:00 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/plugin/in_forward.rb:107:in `run'
```

**Comment by tagomoris** [comment]
It's not an issue of this plugin.
Are you using Fluentd v0.14 and its `forward` plugin as data source?
If so, specify `time_as_integer true` in its configuration.
http://www.fluentd.org/blog/fluentd-v0.14.9-has-been-released
